<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>ARIMA</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Pronósticos</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="analisis.html">Análisis de la serie</a>
</li>
<li>
  <a href="regresion.html">Regresión</a>
</li>
<li>
  <a href="descomposicion.html">Descomposición</a>
</li>
<li>
  <a href="exposmooth.html">Suavización exponencial</a>
</li>
<li>
  <a href="arima.html">ARIMA</a>
</li>
<li>
  <a href="Resumen.html">Resumen</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">ARIMA</h1>

</div>


<div id="section" class="section level2">
<h2></h2>
</div>
<div id="validacion-de-estacionariedad" class="section level2">
<h2>1. Validación de estacionariedad</h2>
</div>
<div id="section-1" class="section level2">
<h2></h2>
<p>Cuando se realizó el análisis de serie, se concluyó que ésta tenía componentes de tendencia y estacionalidad. Por tanto, la serie no es estacionaria, por lo que no se puede aplicar la técnica ARIMA sin lograr previamente la estacionariedad. La no existencia de estacionariedad se confirmará con la prueba KPSS.</p>
<pre class="r"><code>tseries::kpss.test(datos.training)</code></pre>
<pre><code>## Warning in tseries::kpss.test(datos.training): p-value smaller than printed
## p-value</code></pre>
<pre><code>## 
##  KPSS Test for Level Stationarity
## 
## data:  datos.training
## KPSS Level = 1.6667, Truncation lag parameter = 3, p-value = 0.01</code></pre>
<div id="section-2" class="section level4">
<h4></h4>
<p>La hipótesis nula de esta prueba es la existencia de estacionariedad. En este caso, dado que el p-Value es menor que 0.05, se tiene suficiente evidencia para rechazar la hipótesis nula y, por tanto, se confirma que la serie no es estacionaria.</p>
</div>
<div id="section-3" class="section level4">
<h4></h4>
<p>Del análisis de la serie también se observó que el componete estacional no era uniforme, sino que se acentuaba a medida que avanzaba en el tiempo. Por tanto, para regularizar (uniformizar) la magnitud de la estacionalidad, será necesario aplicar una transformación a la serie.</p>
</div>
</div>
<div id="section-4" class="section level2">
<h2></h2>
</div>
<div id="transformacion-y-diferenciacion-de-la-serie" class="section level2">
<h2>2. Transformación y diferenciación de la serie</h2>
</div>
<div id="section-5" class="section level2">
<h2></h2>
<pre class="r"><code>l.datos.training &lt;- log(datos.training)
panel.datos &lt;- cbind(&quot;Serie original&quot; = datos.training, &quot;Transformación Log&quot; = l.datos.training)
autoplot(panel.datos, facets = TRUE)</code></pre>
<p><img src="arima_files/figure-html/unnamed-chunk-2-1.png" width="672" /> ####</p>
<p>El gráfico anterior confirma que se cumplió el objetivo de regularizar la amplitud de la estacionalidad a través de toda la serie.</p>
<div id="section-6" class="section level4">
<h4></h4>
<pre class="r"><code>forecast::ndiffs(l.datos.training)</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>forecast::nsdiffs(l.datos.training)</code></pre>
<pre><code>## [1] 1</code></pre>
</div>
<div id="section-7" class="section level4">
<h4></h4>
<p>Las funciones ndiffs y nsdiffs nos sugieren diferenciar una vez regualarmente y una vez estacionalmente para lograr estacionariedad.</p>
</div>
<div id="section-8" class="section level4">
<h4></h4>
<pre class="r"><code>datos.diferenciados &lt;- diff(diff(l.datos.training,12))
tseries::kpss.test(datos.diferenciados)</code></pre>
<pre><code>## Warning in tseries::kpss.test(datos.diferenciados): p-value greater than
## printed p-value</code></pre>
<pre><code>## 
##  KPSS Test for Level Stationarity
## 
## data:  datos.diferenciados
## KPSS Level = 0.053693, Truncation lag parameter = 3, p-value = 0.1</code></pre>
</div>
<div id="section-9" class="section level4">
<h4></h4>
<p>El resultado de la prueba KPSS a la serie diferenciada regular y estacionalmente confirma que se ha conseguido estacionariedad, por lo que se puede proceder a aplicar la técnica ARIMA.</p>
</div>
</div>
<div id="section-10" class="section level2">
<h2></h2>
</div>
<div id="construccion-de-los-modelos" class="section level2">
<h2>3. Construcción de los modelos</h2>
</div>
<div id="section-11" class="section level2">
<h2></h2>
<pre class="r"><code>ggtsdisplay(datos.diferenciados)</code></pre>
<p><img src="arima_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<div id="section-12" class="section level4">
<h4></h4>
<p>El análisis de los autocorrelogramas construidos sobre la serie transformada y estacionaria sugiere que se puede partir de un modelo ARIMA(1,1,1)(0,1,0) o ARIMA(1,1,1)(1,1,0) y también es plausible probar un modelo ARIMA(2,1,1)(0,1,0) o ARIMA(2,1,1)(1,1,0) Recuérdese que las diferenciaciones regulares y estacionales no se sacan de la lectura de los autocorrelogramas, sino de la necesidad de haber diferenciado la serie para hacerla estacionaria.</p>
</div>
<div id="section-13" class="section level4">
<h4></h4>
<pre class="r"><code>arima1 &lt;- forecast::Arima(l.datos.training, order = c(1,1,1), seasonal = c(0,1,0))
arima1</code></pre>
<pre><code>## Series: l.datos.training 
## ARIMA(1,1,1)(0,1,0)[4] 
## 
## Coefficients:
##          ar1      ma1
##       0.2802  -1.0000
## s.e.  0.1262   0.0478
## 
## sigma^2 estimated as 0.006658:  log likelihood=63.39
## AIC=-120.78   AICc=-120.35   BIC=-114.55</code></pre>
<pre class="r"><code>forecast::checkresiduals(arima1)</code></pre>
<p><img src="arima_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,1,1)(0,1,0)[4]
## Q* = 23.557, df = 6, p-value = 0.0006299
## 
## Model df: 2.   Total lags used: 8</code></pre>
<pre class="r"><code>arima2 &lt;- forecast::Arima(l.datos.training, order = c(1,1,1), seasonal = c(1,1,0))
arima2</code></pre>
<pre><code>## Series: l.datos.training 
## ARIMA(1,1,1)(1,1,0)[4] 
## 
## Coefficients:
##          ar1      ma1     sar1
##       0.4575  -1.0000  -0.5775
## s.e.  0.1235   0.0511   0.1083
## 
## sigma^2 estimated as 0.004624:  log likelihood=73.65
## AIC=-139.3   AICc=-138.56   BIC=-130.99</code></pre>
<pre class="r"><code>forecast::checkresiduals(arima2)</code></pre>
<p><img src="arima_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,1,1)(1,1,0)[4]
## Q* = 8.8538, df = 5, p-value = 0.115
## 
## Model df: 3.   Total lags used: 8</code></pre>
<pre class="r"><code>arima3 &lt;- forecast::Arima(l.datos.training, order = c(2,1,1), seasonal = c(0,1,0))
arima3</code></pre>
<pre><code>## Series: l.datos.training 
## ARIMA(2,1,1)(0,1,0)[4] 
## 
## Coefficients:
##          ar1     ar2      ma1
##       0.2546  0.1058  -1.0000
## s.e.  0.1298  0.1328   0.0468
## 
## sigma^2 estimated as 0.006727:  log likelihood=63.71
## AIC=-119.42   AICc=-118.67   BIC=-111.11</code></pre>
<pre class="r"><code>forecast::checkresiduals(arima3)</code></pre>
<p><img src="arima_files/figure-html/unnamed-chunk-6-3.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(2,1,1)(0,1,0)[4]
## Q* = 22.866, df = 5, p-value = 0.000358
## 
## Model df: 3.   Total lags used: 8</code></pre>
<pre class="r"><code>arima4 &lt;- forecast::Arima(l.datos.training, order = c(2,1,1), seasonal = c(1,1,0))
arima4</code></pre>
<pre><code>## Series: l.datos.training 
## ARIMA(2,1,1)(1,1,0)[4] 
## 
## Coefficients:
##          ar1     ar2      ma1     sar1
##       0.4199  0.0978  -1.0000  -0.5707
## s.e.  0.1339  0.1367   0.0491   0.1085
## 
## sigma^2 estimated as 0.004693:  log likelihood=73.91
## AIC=-137.81   AICc=-136.68   BIC=-127.43</code></pre>
<pre class="r"><code>forecast::checkresiduals(arima4)</code></pre>
<p><img src="arima_files/figure-html/unnamed-chunk-6-4.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(2,1,1)(1,1,0)[4]
## Q* = 8.2823, df = 4, p-value = 0.08177
## 
## Model df: 4.   Total lags used: 8</code></pre>
</div>
<div id="section-14" class="section level4">
<h4></h4>
<p>Los modelos arima1 y arima3 no son válidos, pues los residuos no cumplen con ser ruido blanco. Los modelos arima2 y arima4 sí son válidos pues los residuos son ruido blanco. Entre esos dos, el modelo arima2 es ligeramente mejor al tener un AICc = -138.56.</p>
</div>
<div id="section-15" class="section level4">
<h4></h4>
<pre class="r"><code>library(forecast)
arima.automatico &lt;- auto.arima(l.datos.training, stepwise = FALSE, approximation = FALSE, trace = FALSE)
arima.automatico</code></pre>
<pre><code>## Series: l.datos.training 
## ARIMA(1,0,0)(1,1,2)[4] with drift 
## 
## Coefficients:
##          ar1     sar1     sma1     sma2   drift
##       0.3757  -0.8202  -0.1524  -0.7113  0.0129
## s.e.  0.1295   0.3505   0.4210   0.4382  0.0006
## 
## sigma^2 estimated as 0.003596:  log likelihood=82.46
## AIC=-152.92   AICc=-151.34   BIC=-140.35</code></pre>
<pre class="r"><code>forecast::checkresiduals(arima.automatico)</code></pre>
<p><img src="arima_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,0,0)(1,1,2)[4] with drift
## Q* = 4.8335, df = 3, p-value = 0.1844
## 
## Model df: 5.   Total lags used: 8</code></pre>
</div>
<div id="section-16" class="section level4">
<h4></h4>
<p>La recomendación de auto.arima proporciona un modelo mejor al construido por nosotros (AICc = -151.34) y la prueba de los residuos nos confirma que son ruido blanco. Por tanto, el modelo a ocupar sería ARIMA(1,0,0)(1,1,2).</p>
</div>
</div>
<div id="section-17" class="section level2">
<h2></h2>
</div>
<div id="calculo-del-error-del-pronostico" class="section level2">
<h2>4. Cálculo del error del pronóstico</h2>
</div>
<div id="section-18" class="section level2">
<h2></h2>
<pre class="r"><code>l.pronostico.arima &lt;- forecast(arima.automatico, h = 4)
l.pronostico.arima$mean</code></pre>
<pre><code>##          Qtr1     Qtr2     Qtr3     Qtr4
## 2015 4.284767 3.819411 4.052879 4.140149</code></pre>
<pre class="r"><code>pronostico.arima &lt;- exp(l.pronostico.arima$mean)
pronostico.arima</code></pre>
<pre><code>##          Qtr1     Qtr2     Qtr3     Qtr4
## 2015 72.58564 45.57734 57.56294 62.81218</code></pre>
<pre class="r"><code>mae.arima &lt;- Metrics::mae(datos.test, pronostico.arima)
mse.arima &lt;- Metrics::mse(datos.test, pronostico.arima)
errores.arima &lt;- c(mae.arima, mse.arima)
errores.arima &lt;- matrix(errores.arima, 1, 2)
colnames(errores.arima) &lt;- c(&quot;MAE&quot;, &quot;MSE&quot;)
rownames(errores.arima) &lt;- &quot;Mejor ARIMA&quot;
knitr::kable(errores.arima)</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">MAE</th>
<th align="right">MSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mejor ARIMA</td>
<td align="right">2.392268</td>
<td align="right">6.989476</td>
</tr>
</tbody>
</table>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
